### ISSUE TITLE
DataEntry dropdown not work on Windows10 Python 3.6.5 with tkcalendar 1.2.1

### ISSUE THREAD

**Issue by mottymu** [j4321/tkcalendar#17]
I use Python 3.6.5
and tkcalendar 1.2.1

when I use DateEntry() and click on dropdown button
it nothing happen and got this error

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python36-64\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "C:\Python36-64\lib\site-packages\tkcalendar.py", line 895, in _on_b1_press
    self.drop_down()
  File "C:\Python36-64\lib\site-packages\tkcalendar.py", line 967, in drop_down
    self._validate_date()
  File "C:\Python36-64\lib\site-packages\tkcalendar.py", line 926, in _validate_date
    self._date = self._calendar.strptime(self.get(), '%x').date()
  File "C:\Python36-64\lib\_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "C:\Python36-64\lib\_strptime.py", line 345, in _strptime
    format_regex = _TimeRE_cache.compile(format)
  File "C:\Python36-64\lib\_strptime.py", line 275, in compile
    return re_compile(self.pattern(format), IGNORECASE)
  File "C:\Python36-64\lib\re.py", line 233, in compile
    return _compile(pattern, flags)
  File "C:\Python36-64\lib\re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Python36-64\lib\sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Python36-64\lib\sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Python36-64\lib\sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "C:\Python36-64\lib\sre_parse.py", line 759, in _parse
    raise source.error(err.msg, len(name) + 1) from None
sre_constants.error: redefinition of group name 'w' as group 4; was group 3 at position 87

what I have to do?

Thank you.

**Comment by j4321** [comment]
Ok, thanks for the feedback, right now I have no idea what is causing your issue. Can you give me a full snippet of code that reproduces the error you got and tell me how you ran it (python console, IDLE, ...)?

**Comment by j4321** [comment]
Could you try [this version](https://github.com/j4321/tkcalendar/tree/fix-%2315) of the code and tell me if you still have the error?

**Comment by mottymu** [comment]
I tried to use Python 3.4/3.6.5/3.7 and my IDE are Pycharm Pro and Sublime text 3 all of them got the same error.

And link that you post I can't download. Could you post new link?

**Comment by j4321** [comment]
Ok, sorry about the download link, I merged the branch with master and deleted it. You can now directly try the code from the [master](https://github.com/j4321/tkcalendar/archive/master.zip) branch. 

I had feedback from another Windows user for whom everything works fine and I also use Appveyor to run tests on Windows (with python 2.7, 3.4, 3.5 and 3.6), so I really have no clue why this i not working for you. I hope that using babel module (needs to be installed) will solve your issue.
